//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaerskLineCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.deliveryInvoices = new HashSet<deliveryInvoice>();
        }
    
        public int customerID { get; set; }
        public string customerEmail { get; set; }
        public string customerName { get; set; }
        public string customerIC { get; set; }
        public Nullable<bool> customerGender { get; set; }
        public string customerPhoneNo { get; set; }
        public string customerAddress { get; set; }
        public string customerAddressCountry { get; set; }
        public int agentID { get; set; }
    
        public virtual agent agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliveryInvoice> deliveryInvoices { get; set; }
    }
}
