//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaerskLineCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveryInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public deliveryInvoice()
        {
            this.items = new HashSet<item>();
        }
    
        public int deliveryInvoiceID { get; set; }
        public int scheduleBookingID { get; set; }
        public int agentID { get; set; }
        public int customerID { get; set; }
        public decimal invoiceTEU { get; set; }
    
        public virtual agent agent { get; set; }
        public virtual customer customer { get; set; }
        public virtual scheduleBooking scheduleBooking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item> items { get; set; }
    }
}
