//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaerskLineCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int itemID { get; set; }
        public string itemName { get; set; }
        public string itemCategory { get; set; }
        public decimal itemVolume { get; set; }
        public decimal itemMass { get; set; }
        public int deliveryInvoiceID { get; set; }
    
        public virtual deliveryInvoice deliveryInvoice { get; set; }
    }
}
