//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaerskLineCMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaerskLineContainerManagementSystemEntities : DbContext
    {
        public MaerskLineContainerManagementSystemEntities()
            : base("name=MaerskLineContainerManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<agent> agents { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<deliveryInvoice> deliveryInvoices { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<scheduleBooking> scheduleBookings { get; set; }
        public virtual DbSet<ship> ships { get; set; }
    }
}
