//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaerskLineCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public schedule()
        {
            this.scheduleBookings = new HashSet<scheduleBooking>();
        }
    
        public int scheduleID { get; set; }
        public string scheduleDetail { get; set; }
        public string scheduleDeparture { get; set; }
        public System.DateTime scheduleDepartureDate { get; set; }
        public System.TimeSpan scheduleDepartureTime { get; set; }
        public string scheduleArrival { get; set; }
        public System.DateTime scheduleArrivalDate { get; set; }
        public System.TimeSpan scheduleArrivalTime { get; set; }
        public int shipID { get; set; }
        public int adminID { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual ship ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scheduleBooking> scheduleBookings { get; set; }
    }
}
