//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaerskLineCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduleBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public scheduleBooking()
        {
            this.deliveryInvoices = new HashSet<deliveryInvoice>();
        }
    
        public int scheduleBookingID { get; set; }
        public int scheduleID { get; set; }
        public int agentID { get; set; }
        public string status { get; set; }
        public decimal requiredTEU { get; set; }
    
        public virtual agent agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliveryInvoice> deliveryInvoices { get; set; }
        public virtual schedule schedule { get; set; }
    }
}
